<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access control' => 'Управление доступом',
    'Blogs' => 'Блоги',
	'Cities' => 'Города',
    'Comments' => 'Комментарии',
    'Dashboard' => 'Панель управления',
    'Hello, {name}' => 'Здравствуйте, {name}',
    'Home' => 'Главная',
    'Hubs' => 'Хабы',
    'Member since' => 'Зарегестрирован с',
    'Models management' => 'Управления моделями',
    'Online' => 'Онлайн',
    'Permissions' => 'Права',
    'Profile' => 'Профиль',
	'Regions' => 'Регионы',
    'Provinces' => 'Провинции',
    'Roles' => 'Роли',
    'Rules' => 'Правила',
    'Sign out' => 'Выход',
    'Toggle navigation' => 'Показать/Скрыть меню',
    'Users' => 'Пользователи',
    'Feedback' => 'Feedback',
    'Faq' => 'FAQ',
    'Static Pages' => 'Статичные страницы',
    'Lang' => 'Языки',
    'Translations' => 'Переводы',
    'Directories' => 'Справочники',
    'PlacementTypes' => 'Типы размещения',
    'Placements' => 'Места размещения',
    'Restaurants' => 'Рестораны',
    'Showplaces' => 'Достопримечательности',
    'ShowplacesTypes' => 'Типы достопримечательностей',
    'TourTypes' => 'Типы туров',
    'Tours' => 'Туры',
    'Tour' => 'Тур',
    'Geo' => 'География',
    'Placement' => 'Размещения',
    'Places' => 'Места',
    'Room' => 'Номерной фонд',
    'Cafes' => 'Кафе',
    'Shops' => 'Магазины',
    'ShopTypes' => 'Типы магазинов',
    'Shop-categories' => 'Категории магазинов',
    'Market-categories' => 'Категории рынков',
    'GO_TO_SITE' => 'Перейти на сайт',
    'POINT_ON_MAP' => 'Указать на карте',
    'IMAGE_MESSAGE_FILE_TYPES' => 'Недопустимый тип файла',
    'PlacementOptions' => 'Опции отелей',
    'RoomType' => 'Типы номеров',
    'RoomOptions' => 'Опции номеров',
    'TourOptions' => 'Опции туров',
    'TABS_CHAR' => 'Основные характеристики',
];
